<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>NepTunnel</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWPF>True</UseWPF>
    <TargetFramework>net8.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="bundled_assets\nepnamesyncscript.luau" />
    <None Remove="bundled_assets\nepclientleaderboard.luau" />
    <None Remove="bundled_assets\logo.png" />
    <None Remove="bundled_assets\nepservernamesync.luau" />
    <None Remove="bundled_assets\robloxstudiomodmanager.exe" />
    <None Remove="mainwindow.baml" />
    <None Remove="bundled_assets\nepbridgeplugin.lua" />
    <None Remove="bundled_assets\tut_8.png" />
    <None Remove="bundled_assets\tut_9.png" />
    <None Remove="bundled_assets\tut_4.png" />
    <None Remove="bundled_assets\tut_6.png" />
    <None Remove="bundled_assets\tut_5.png" />
    <None Remove="bundled_assets\tut_7.png" />
    <None Remove="bundled_assets\tut_2.png" />
    <None Remove="bundled_assets\tut_1.png" />
    <None Remove="bundled_assets\tut_3.png" />
    <None Remove="bundled_assets\default_baseplate.rbxlx" />
    <None Remove="app.baml" />
    <None Remove="icon.ico" />
    <None Remove="bundled_assets\banner.jpg" />
    <EmbeddedResource Include="bundled_assets\nepnamesyncscript.luau" LogicalName="bundled_assets/nepnamesyncscript.luau" />
    <EmbeddedResource Include="bundled_assets\nepclientleaderboard.luau" LogicalName="bundled_assets/nepclientleaderboard.luau" />
    <EmbeddedResource Include="bundled_assets\logo.png" LogicalName="bundled_assets/logo.png" />
    <EmbeddedResource Include="bundled_assets\nepservernamesync.luau" LogicalName="bundled_assets/nepservernamesync.luau" />
    <EmbeddedResource Include="bundled_assets\robloxstudiomodmanager.exe" LogicalName="bundled_assets/robloxstudiomodmanager.exe" />
    <EmbeddedResource Include="mainwindow.baml" LogicalName="mainwindow.baml" />
    <EmbeddedResource Include="bundled_assets\nepbridgeplugin.lua" LogicalName="bundled_assets/nepbridgeplugin.lua" />
    <EmbeddedResource Include="bundled_assets\tut_8.png" LogicalName="bundled_assets/tut_8.png" />
    <EmbeddedResource Include="bundled_assets\tut_9.png" LogicalName="bundled_assets/tut_9.png" />
    <EmbeddedResource Include="bundled_assets\tut_4.png" LogicalName="bundled_assets/tut_4.png" />
    <EmbeddedResource Include="bundled_assets\tut_6.png" LogicalName="bundled_assets/tut_6.png" />
    <EmbeddedResource Include="bundled_assets\tut_5.png" LogicalName="bundled_assets/tut_5.png" />
    <EmbeddedResource Include="bundled_assets\tut_7.png" LogicalName="bundled_assets/tut_7.png" />
    <EmbeddedResource Include="bundled_assets\tut_2.png" LogicalName="bundled_assets/tut_2.png" />
    <EmbeddedResource Include="bundled_assets\tut_1.png" LogicalName="bundled_assets/tut_1.png" />
    <EmbeddedResource Include="bundled_assets\tut_3.png" LogicalName="bundled_assets/tut_3.png" />
    <EmbeddedResource Include="bundled_assets\default_baseplate.rbxlx" LogicalName="bundled_assets/default_baseplate.rbxlx" />
    <EmbeddedResource Include="app.baml" LogicalName="app.baml" />
    <EmbeddedResource Include="icon.ico" LogicalName="icon.ico" />
    <EmbeddedResource Include="bundled_assets\banner.jpg" LogicalName="bundled_assets/banner.jpg" />
  </ItemGroup>
  <ItemGroup />
</Project>