using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;
using System.Windows.Resources;

[assembly: AssemblyAssociatedContentFile("bundled_assets/banner.jpg")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/default_baseplate.rbxlx")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/logo.png")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/nepbridgeplugin.lua")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/nepclientleaderboard.luau")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/nepnamesyncscript.luau")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/nepservernamesync.luau")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/robloxstudiomodmanager.exe")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/tut_1.png")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/tut_2.png")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/tut_3.png")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/tut_4.png")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/tut_5.png")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/tut_6.png")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/tut_7.png")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/tut_8.png")]
[assembly: AssemblyAssociatedContentFile("bundled_assets/tut_9.png")]
[assembly: AssemblyCompany("NepTunnel")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0+b998e09231d9f262894a31d9ce7d5f83da4dcd7d")]
[assembly: AssemblyProduct("NepTunnel")]
[assembly: AssemblyTitle("NepTunnel")]
[assembly: TargetPlatform("Windows7.0")]
[assembly: SupportedOSPlatform("Windows7.0")]
[assembly: AssemblyVersion("1.0.0.0")]
